// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_sistem_peminjaman_ruangan_backend.Data;

#nullable disable

namespace _2026_sistem_peminjaman_ruangan_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214011422_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2026_sistem_peminjaman_ruangan_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalPeminjaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Peminjaman");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keperluan = "Praktikum Tambahan",
                            NamaPeminjam = "Budi Santoso",
                            Ruangan = "Lab Komputer 1",
                            Status = "Menunggu",
                            TanggalPeminjaman = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Keperluan = "Seminar Mahasiswa",
                            NamaPeminjam = "Siti Aminah",
                            Ruangan = "Aula Besar",
                            Status = "Disetujui",
                            TanggalPeminjaman = new DateTime(2026, 2, 25, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
